/*
     Title: Constent for StyleWiseCostingSummary
     Description: Constent for StyleWiseCostingSummary
     Author: Iqbal Hossain
     Date: 06-August-2022
     Modified: 06-August-2022
*/

export const FETCH_STYLE_WISE_COSTING_SUMMARY = 'FETCH_STYLE_WISE_COSTING_SUMMARY';
export const FETCH_BUYER_COSTING_SUMMARY = 'FETCH_BUYER_COSTING_SUMMARY';
export const FETCH_DEPARTMENT_COSTING_SUMMARY = 'FETCH_DEPARTMENT_COSTING_SUMMARY';
export const FETCH_YEAR_COSTING_SUMMARY = 'FETCH_YEAR_COSTING_SUMMARY';
export const FETCH_SEASON_COSTING_SUMMARY = 'FETCH_SEASON_COSTING_SUMMARY';
export const FETCH_STYLE_COSTING_SUMMARY = 'FETCH_STYLE_COSTING_SUMMARY';
export const BUYER_CHANGE_COSTING_SUMMARY = 'BUYER_CHANGE_COSTING_SUMMARY';
export const DEPARTMENT_CHANGE_COSTING_SUMMARY = 'DEPARTMENT_CHANGE_COSTING_SUMMARY';
export const YEAR_CHANGE_COSTING_SUMMARY = 'YEAR_CHANGE_COSTING_SUMMARY';
export const SEASON_CHANGE_COSTING_SUMMARY = 'SEASON_CHANGE_COSTING_SUMMARY';
export const STYLE_CHANGE_COSTING_SUMMARY = 'STYLE_CHANGE_COSTING_SUMMARY';
export const LOADING = 'LOADING';
