// import './inventory/itemGroupApi';
// import './inventory/itemSubGroupApi';
// import './inventory/segmentApi';
import './jwt';
// import './merchandising/bomApi';
// import './merchandising/budgetApi';
// import './merchandising/buyerAgentApi';
// import './merchandising/buyerApi';
// import './merchandising/buyerDepartmentApi';
// import './merchandising/calendar';
// import './merchandising/consumptionApi';
// import './merchandising/chat';
// import './merchandising/colorApi';
// import './merchandising/departmentApi';
// import './merchandising/divisionApi';
// import './merchandising/eCommerce';
// import './merchandising/email';
// import './merchandising/invoice';
// import './merchandising/merchandiserApi';
// import './merchandising/moduleApi';
// import './merchandising/preCostingApi';
// import './merchandising/productCategoryApi';
// import './merchandising/productDeveloperApi';
// import './merchandising/purchaseOrderApi';
// import './merchandising/roleApi';
// import './merchandising/sampleAssigneeApi';
// import './merchandising/seasonApi';
// import './merchandising/setStyleApi';
// import './merchandising/statusApi';
// import './merchandising/sizeApi';
// import './merchandising/sizeGroupApi';
// import './merchandising/statusApi';
// import './merchandising/styleApi';
// import './merchandising/styleCategoryApi';
// import './merchandising/todo';
// import './merchandising/userApi';
// import './merchandising/userList';
import mock from './mock';

mock.onAny().passThrough();
