/*
     Title: Constent for StyleSummaryBuyerAndStyleWise
     Description: Constent for StyleSummaryBuyerAndStyleWise
     Author: Iqbal Hossain
     Date: 06-August-2022
     Modified: 06-August-2022
*/

export const FETCH_MATERIAL_STATUS_STYLE_AND_PO_WISE_BUYER_AND_STYLE_WISE = 'FETCH_MATERIAL_STATUS_STYLE_AND_PO_WISE_BUYER_AND_STYLE_WISE';
export const FETCH_MATERIAL_STATUS_STYLE_AND_PO_WISE_BUYER_AND_STYLE_ITEM_DETAILS =
  'FETCH_MATERIAL_STATUS_STYLE_AND_PO_WISE_BUYER_AND_STYLE_ITEM_DETAILS';

export const FETCH_PURCHASE_ORDER_BY_STYLE_ID_MATERIAL_STATUS = 'FETCH_PURCHASE_ORDER_BY_STYLE_ID_MATERIAL_STATUS';
export const PURCHASE_ORDER_CHANGE_MATERIAL_STATUS = 'PURCHASE_ORDER_CHANGE_MATERIAL_STATUS';

export const FETCH_BUYER_MATERIAL_STATUS_STYLE_AND_PO_WISE = 'FETCH_BUYER_MATERIAL_STATUS_STYLE_AND_PO_WISE';
export const BUYER_CHANGE_MATERIAL_STATUS_STYLE_AND_PO_WISE = 'BUYER_CHANGE_MATERIAL_STATUS_STYLE_AND_PO_WISE';


export const FETCH_STYLE_MATERIAL_STATUS_STYLE_AND_PO_WISE = 'FETCH_STYLE_MATERIAL_STATUS_STYLE_AND_PO_WISE';
export const STYLE_CHANGE_MATERIAL_STATUS_STYLE_AND_PO_WISE = 'STYLE_CHANGE_MATERIAL_STATUS_STYLE_AND_PO_WISE';

export const LOADING = 'LOADING';
