/*
     Title: Constent for PurchaseOrder
     Description: Constent for PurchaseOrder
     Author: Iqbal Hossain
     Date: 22-August-2022
     Modified: 22-August-2022
*/

export const FETCH_PURCHASE_ORDER_STYLE_AND_ITEM_WISE = 'FETCH_PURCHASE_ORDER_STYLE_AND_ITEM_WISE';
export const FETCH_PURCHASE_ORDER_STYLE_AND_PO_WISE = 'FETCH_PURCHASE_ORDER_STYLE_AND_PO_WISE';

export const FETCH_ALL_PO_BY_SO_STYLE_AND_ITEM_WISE = 'FETCH_ALL_PO_BY_SO_STYLE_AND_ITEM_WISE';
export const PURCHASE_ORDER_CHANGE_PO_SO_STYLE_AND_ITEM_WISE = 'PURCHASE_ORDER_CHANGE_PO_SO_STYLE_AND_ITEM_WISE';

export const STYLE_CHANGE_PO_SO_STYLE_AND_ITEM_WISE = 'STYLE_CHANGE_PO_SO_STYLE_AND_ITEM_WISE';


export const FETCH_BUYER_PURCHASE_ORDER_STYLE_AND_ITEM_WISE = 'FETCH_BUYER_PURCHASE_ORDER_STYLE_AND_ITEM_WISE';
export const BUYER_CHANGE_PURCHASE_ORDER_STYLE_AND_ITEM_WISE = 'BUYER_CHANGE_PURCHASE_ORDER_STYLE_AND_ITEM_WISE';


export const FETCH_STYLE_PURCHASE_ORDER_STYLE_AND_ITEM_WISE = 'FETCH_STYLE_PURCHASE_ORDER_STYLE_AND_ITEM_WISE';
export const STYLE_CHANGE_PURCHASE_ORDER_STYLE_AND_ITEM_WISE = 'STYLE_CHANGE_PURCHASE_ORDER_STYLE_AND_ITEM_WISE';

export const LOADING = 'LOADING';
