/*
     Title: Constent for OrderSummaryPOAndSytleWise
     Description: Constent for OrderSummaryPOAndSytleWise
     Author: Iqbal Hossain
     Date: 07-August-2022
     Modified: 07-August-2022
*/

export const FETCH_ORDER_SUMMARY_PO_AND_STYLE_WISE = 'FETCH_ORDER_SUMMARY_PO_AND_STYLE_WISE';
export const FETCH_BUYER_ORDER_SUMMARY_PO_STYLE_WISE = 'FETCH_BUYER_ORDER_SUMMARY_PO_STYLE_WISE';
export const FETCH_DEPARTMENT_ORDER_SUMMARY_PO_STYLE_WISE = 'FETCH_DEPARTMENT_ORDER_SUMMARY_PO_STYLE_WISE';
export const FETCH_YEAR_ORDER_SUMMARY_PO_STYLE_WISE = 'FETCH_YEAR_ORDER_SUMMARY_PO_STYLE_WISE';
export const FETCH_SEASON_ORDER_SUMMARY_PO_STYLE_WISE = 'FETCH_SEASON_ORDER_SUMMARY_PO_STYLE_WISE';
export const FETCH_STYLE_ORDER_SUMMARY_PO_STYLE_WISE = 'FETCH_STYLE_ORDER_SUMMARY_PO_STYLE_WISE';
export const BUYER_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE = 'BUYER_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE';
export const DEPARTMENT_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE = 'DEPARTMENT_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE';
export const YEAR_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE = 'YEAR_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE';
export const SEASON_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE = 'SEASON_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE';
export const STYLE_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE = 'STYLE_CHANGE_ORDER_SUMMARY_PO_STYLE_WISE';
export const LOADING = 'LOADING';
