/*
  Title: Actions for PostCostSheet
  Description: Actions for PostCostSheet
  Author: Iqbal Hossain
  Date: 21-August-2022
  Modified: 21-August-2022
*/

import { v4 as uuid } from 'uuid';
import { FETCH_POST_COST_SHEET } from './actionType';

//Get Data by Query
export const fetchPostCostSheet = () => async dispatch => {
  const data = {
    buyer: 'MARIKA LLC',
    agent: 'BLL0079T',
    department: 'IN LINE',
    season: 'FALL-17',
    styleId: '',
    masterLcValue: '',
    masterLcNo: '',
    salesContractNo: '',
    salesContractValue: '',
    lcOpenedDate: '',
    bblcNo: '',
    orderQty: '',
    shipmentQty: '',
    excessShort: '',
    shipmentDate: '',
    user: 'uni user',
    reportGeneratedOn: '03-Aug-22 11:33 AM',
    yarnCompositionDetails: [
      {
        id: uuid(),
        yarnComposition: 'GF-17-105',
        weight: '0.76',
        wastage: '5.00',
        totalCon: '0.79800',
        unitPrice: '2.3',
        valueDzn: '27.8',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        yarnComposition: 'GF-17-105',
        weight: '0.00',
        wastage: '5.00',
        totalCon: '0.00441',
        unitPrice: '1.7',
        valueDzn: '20.4',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      }
    ],
    accessoriesDetails: [
      {
        id: uuid(),
        accessories: 'Carton',
        req1: '',
        reqPcs: '/pc',
        req2: '',
        reqDzn: 'pcs',
        unitPrice: '30.0',
        dozen: 'Dozen',
        valuePc: '2.5',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Elastic',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.6',
        dozen: 'Dozen',
        valuePc: '1',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Hang Tag Barcode/Upc',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.4',
        dozen: 'Dozen',
        valuePc: '.0',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Hang Tag Function',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.2',
        dozen: 'Dozen',
        valuePc: '.0',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Heat Seal Care',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.3',
        dozen: 'Dozen',
        valuePc: '.0',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Heat Seal Coo',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.4',
        dozen: 'Dozen',
        valuePc: '.0',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Heat Seal Logo',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.2',
        dozen: 'Dozen',
        valuePc: '.0',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Joker Tag',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.3',
        dozen: 'Dozen',
        valuePc: '.0',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Poly Bag PC',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '.4',
        dozen: 'Dozen',
        valuePc: '.0',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      },
      {
        id: uuid(),
        accessories: 'Sewing Thread',
        req1: '1',
        reqPcs: '/pc',
        req2: '12',
        reqDzn: 'pcs',
        unitPrice: '7.2',
        dozen: 'Dozen',
        valuePc: '.6',
        total: 0,
        piNo: 'CH201703 01-1PI',
        date: '16/17/05',
        piQty: '14,579.46',
        piRate: '2.32',
        piValue: '33,824.35',
        urplusDif: '',
        paymendMode: 'At Sight',
        supplier: 'FUJIAN DUNHUANG IMP. & EXP. INDUSTRY CO. LTD (LDF)'
      }
    ]
  };
  dispatch({
    type: FETCH_POST_COST_SHEET,
    payload: data
  });
};
