/*
     Title: Constent for StyleSummaryBuyerAndStyleWise
     Description: Constent for StyleSummaryBuyerAndStyleWise
     Author: Iqbal Hossain
     Date: 06-August-2022
     Modified: 06-August-2022
*/

export const FETCH_STYLE_SUMMARY_BUYER_AND_STYLE_WISE = 'FETCH_STYLE_SUMMARY_BUYER_AND_STYLE_WISE';
export const FETCH_BUYER_STYLE_SUMMARY = 'FETCH_BUYER_STYLE_SUMMARY';
export const FETCH_DEPARTMENT_STYLE_SUMMARY = 'FETCH_DEPARTMENT_STYLE_SUMMARY';
export const FETCH_YEAR_STYLE_SUMMARY = 'FETCH_YEAR_STYLE_SUMMARY';
export const FETCH_SEASON_STYLE_SUMMARY = 'FETCH_SEASON_STYLE_SUMMARY';
export const FETCH_STYLE_STYLE_SUMMARY = 'FETCH_STYLE_STYLE_SUMMARY';
export const BUYER_CHANGE_STYLE_SUMMARY = 'BUYER_CHANGE_STYLE_SUMMARY';
export const DEPARTMENT_CHANGE_STYLE_SUMMARY = 'DEPARTMENT_CHANGE_STYLE_SUMMARY';
export const YEAR_CHANGE_STYLE_SUMMARY = 'YEAR_CHANGE_STYLE_SUMMARY';
export const SEASON_CHANGE_STYLE_SUMMARY = 'SEASON_CHANGE_STYLE_SUMMARY';
export const STYLE_CHANGE_STYLE_SUMMARY = 'STYLE_CHANGE_STYLE_SUMMARY';
export const LOADING = 'LOADING';
