/*
     Title: Constent for PreCosting Sheet
     Description: Constent for PreCosting Sheet
     Author: Iqbal Hossain
     Date: 04-August-2022
     Modified: 04-August-2022
*/

export const FETCH_PRE_COSTING_SHEET = 'FETCH_PRE_COSTING_SHEET';
export const FETCH_BUYER_PRE_COSTING_SHEET = 'FETCH_BUYER_PRE_COSTING_SHEET';
export const FETCH_DEPARTMENT_PRE_COSTING_SHEET = 'FETCH_DEPARTMENT_PRE_COSTING_SHEET';
export const FETCH_YEAR_PRE_COSTING_SHEET = 'FETCH_YEAR_PRE_COSTING_SHEET';
export const FETCH_SEASON_PRE_COSTING_SHEET = 'FETCH_SEASON_PRE_COSTING_SHEET';
export const FETCH_STYLE_PRE_COSTING_SHEET = 'FETCH_STYLE_PRE_COSTING_SHEET';
export const FETCH_COSTING_BY_STYLE = 'FETCH_COSTING_BY_STYLE';
export const BUYER_CHANGE_PRE_COSTING_SHEET = 'BUYER_CHANGE_PRE_COSTING_SHEET';
export const DEPARTMENT_CHANGE_PRE_COSTING_SHEET = 'DEPARTMENT_CHANGE_PRE_COSTING_SHEET';
export const YEAR_CHANGE_PRE_COSTING_SHEET = 'YEAR_CHANGE_PRE_COSTING_SHEET';
export const SEASON_CHANGE_PRE_COSTING_SHEET = 'SEASON_CHANGE_PRE_COSTING_SHEET';
export const STYLE_CHANGE_PRE_COSTING_SHEET = 'STYLE_CHANGE_PRE_COSTING_SHEET';
export const COSTING_BY_STYLE_CHANGE = 'COSTING_BY_STYLE_CHANGE';
export const LOADING = 'LOADING';
