/*
     Title: Constent for ExportPoWithColorAndSize
     Description: Constent for ExportPoWithColorAndSize
     Author: Iqbal Hossain
     Date: 06-August-2022
     Modified: 06-August-2022
*/

export const FETCH_EXPORT_PO_WITH_COLOR_AND_SIZE = 'FETCH_EXPORT_PO_WITH_COLOR_AND_SIZE';
export const FETCH_BUYER_PO_WITH_COLOR_SIZE = 'FETCH_BUYER_PO_WITH_COLOR_SIZE';
export const FETCH_DEPARTMENT_PO_WITH_COLOR_SIZE = 'FETCH_DEPARTMENT_PO_WITH_COLOR_SIZE';
export const FETCH_YEAR_PO_WITH_COLOR_SIZE = 'FETCH_YEAR_PO_WITH_COLOR_SIZE';
export const FETCH_SEASON_PO_WITH_COLOR_SIZE = 'FETCH_SEASON_PO_WITH_COLOR_SIZE';
export const FETCH_STYLE_PO_WITH_COLOR_SIZE = 'FETCH_STYLE_PO_WITH_COLOR_SIZE';
export const BUYER_CHANGE_PO_WITH_COLOR_SIZE = 'BUYER_CHANGE_PO_WITH_COLOR_SIZE';
export const DEPARTMENT_CHANGE_PO_WITH_COLOR_SIZE = 'DEPARTMENT_CHANGE_PO_WITH_COLOR_SIZE';
export const YEAR_CHANGE_PO_WITH_COLOR_SIZE = 'YEAR_CHANGE_PO_WITH_COLOR_SIZE';
export const SEASON_CHANGE_PO_WITH_COLOR_SIZE = 'SEASON_CHANGE_PO_WITH_COLOR_SIZE';
export const STYLE_CHANGE_PO_WITH_COLOR_SIZE = 'STYLE_CHANGE_PO_WITH_COLOR_SIZE';
export const LOADING = 'LOADING';
