/*
     Title: Constent for PurchaseOrder
     Description: Constent for PurchaseOrder
     Author: Iqbal Hossain
     Date: 22-August-2022
     Modified: 22-August-2022
*/

export const FETCH_PURCHASE_ORDER_ITEM_GROUP = 'FETCH_PURCHASE_ORDER_ITEM_GROUP';
export const FETCH_ALL_PO_BY_SO_ITEM_GROUP = 'FETCH_ALL_PO_BY_SO_ITEM_GROUP';
export const PURCHASE_ORDER_CHANGE_PO_SO_ITEM_GROUP = 'PURCHASE_ORDER_CHANGE_PO_SO_ITEM_GROUP';

export const FETCH_BUYER_PURCHASE_ORDER_ITEM_GROUP = 'FETCH_BUYER_PURCHASE_ORDER_ITEM_GROUP';
export const BUYER_CHANGE_PURCHASE_ORDER_ITEM_GROUP = 'BUYER_CHANGE_PURCHASE_ORDER_ITEM_GROUP';


export const FETCH_STYLE_PURCHASE_ORDER_ITEM_GROUP = 'FETCH_STYLE_PURCHASE_ORDER_ITEM_GROUP';
export const STYLE_CHANGE_PURCHASE_ORDER_ITEM_GROUP = 'STYLE_CHANGE_PURCHASE_ORDER_ITEM_GROUP';

export const LOADING = 'LOADING';
