/*
     Title: PI Statement Action Types
     Description: PI Statement Action Types
     Author: Iqbal Hossain
     Date: 25-September-2022
     Modified: 25-September-2022
*/

export const FETCH_PURCHASE_ORDER_PI_STATEMENT = 'FETCH_PURCHASE_ORDER_PI_STATEMENT';

export const FETCH_ALL_PO_BY_SO_PI_STATEMENT = 'FETCH_ALL_PO_BY_SO_PI_STATEMENT';
export const PURCHASE_ORDER_CHANGE_PO_SO_PI_STATEMENT = 'PURCHASE_ORDER_CHANGE_PO_SO_PI_STATEMENT';

export const FETCH_ALL_SUPPLIER_PI_STATEMENT = 'FETCH_ALL_SUPPLIER_PI_STATEMENT';
export const SUPPLIER_PI_STATEMENT_CHANGE_PI_STATEMENT = 'SUPPLIER_PI_STATEMENT_CHANGE_PI_STATEMENT';
export const LOADING = 'LOADING';
